eventtusTask/config/routes.rb
Rails.application.routes.draw do

  post 'packages/search' , :to => 'packages#search'
  resources :packages
  resources :users

  root 'packages#index'

end

eventtusTask/app/models/dependency.rb
class Dependency < ActiveRecord::Base
    belongs_to :package
end

eventtusTask/app/models/package.rb
class Package < ActiveRecord::Base
    validates :name, presence: true
    validates :os, presence: true
    validates_uniqueness_of :name, :scope => :os
    has_many :dependencies, dependent: :destroy
end

eventtusTask/app/models/user.rb
class User < ActiveRecord::Base
    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
end

eventtusTask/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

eventtusTask/app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  protect_from_forgery with: :null_session
  require 'rbconfig'

  def index
    @packages = Package.all
  end

  def new
    @package = Package.new
  end

  def create
    @package = Package.new(package_params)
    @package.save
    if params[:package][:dependencies]
      params[:package][:dependencies].each do |d|
        @dependency = Dependency.new()
        @dependency.name = d
        @dependency.package_id = @package.id
        @dependency.save
      end
    end
    if @package.save
        redirect_to packages_path
    else
        render 'new'
    end
  end

  def show
    @package = Package.find(params[:id])
  end

  def edit
    @package = Package.find(params[:id])
  end

  def update
    @package = Package.find(params[:id])
    if @package.update(package_params)
      if params[:package][:dependencies]
        @package.dependencies.destroy_all
        params[:package][:dependencies].each do |d|
          @dependency = Dependency.new()
          @dependency.name = d
          @dependency.package_id = @package.id
          @dependency.save
        end
      end
      redirect_to packages_path
    else
      render 'edit'
    end
  end

  def destroy
    @package = Package.find(params[:id])
    @package.destroy
    
    redirect_to packages_path
  end

  def search
    @packages = request[:packages]
    @os = request[:os]
    @result = []
    @packages.each do |p|
       if Package.where(name: p).where(os: @os).any?
        @pkg = Package.where(name: p).where(os: @os).first
        @result << @pkg.as_json(include:[:dependencies])
        # break
        # @result << @pkg
       end
    end
    render :json => @result
  end

  private
  def package_params
    params.require(:package).permit(:name, :os)
  end
end

eventtusTask/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        #render plain: params[:user].inspect
        @user = User.new(user_params)
        if @user.save
            redirect_to action: "index"
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to @users_path
        else
          render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        
        redirect_to users_path
    end

    private
    def user_params
        params.require(:user).permit(:name, :email)
    end
end

eventtusTask/app/helpers/application_helper.rb
module ApplicationHelper
end

eventtusTask/app/helpers/packages_helper.rb
module PackagesHelper
end

eventtusTask/app/helpers/users_helper.rb
module UsersHelper
end

eventtusTask/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Eventtus Task" %></title>

    <!-- <%= stylesheet_link_tag    "application" %> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.css">
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
    
    <!-- <%= javascript_include_tag "vendor/modernizr" %> -->
    <%= csrf_meta_tags %>
  </head>

  <body>
      <div class="top-bar" id="example-menu">
        <div class="top-bar-left">
          <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text"><%= link_to 'Eventtus Task', packages_path %></li>
          </ul>
        </div>
        <!-- <div class="top-bar-right">
          <ul class="menu">
            <li><input type="search" placeholder="Search"></li>
            <li><button type="button" class="button">Search</button></li>
          </ul>
        </div> -->
      </div>
    <%= yield %>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/plugins/foundation.core.js"></script>
    <!-- <%= javascript_include_tag "application" %> -->
  </body>
</html>

eventtusTask/app/views/users/index.html.erb
<h1>Users</h1>

<table>
 <tr>
   <th>Name</th>
   <th>Email</th>
 </tr>

 <% @users.each do |user| %>
   <tr>
     <td><%= user.name %></td>
     <td><%= user.email %></td>
     <td><%= link_to 'Show', user_path(user) %></td>
     <td><%= link_to 'Edit', edit_user_path(user) %></td>
     <td><%= link_to 'Destroy', user_path(user),
     method: :delete,
     data: { confirm: 'Are you sure?' } %></td>
   </tr>
 <% end %>
</table>


<%= link_to 'New user', new_user_path %>

eventtusTask/app/views/users/new.html.erb
<h1>New User</h1>

<%= form_tag "/users" do %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
        <h2>
            <%= pluralize(@user.errors.count, "error") %> prohibited
            this user from being saved:
        </h2>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <%= label_tag "Name" %>
    <%= text_field_tag "user[name]" %>
    <%= label_tag "Email" %>
    <%= text_field_tag "user[email]" %>
    <%= submit_tag "Create" %>
<% end %>

eventtusTask/app/views/users/show.html.erb
<h1>User: #<%= @user.id %> </h1>
<p>
<strong>Name:</strong>
<%= @user.name %>
</p>

<p>
<strong>Email:</strong>
<%= @user.email %>
</p>